// DICIONARIO company ARMAZENA AS EMPRESAS A SEREM POPULADAS DO SELECT
// OPCIONAL: USE COMO key O DIGITO INICIAL DOS PREFIXOS DA REFERIDA EMPRESA, AO CARREGAR O ARQUIVO
// SE EXISTIR key CORRESPONDENTE SELECIONA EMPRESA DE FORMA AUTOMATICA 
var company = {
    1: 'VPAR TRANSPORTES',
    2: 'Rápido Cuiabá',
}

var autoSelectCompany = true;